name: Manual Workflow Dispatch

on:
  workflow_dispatch:
    # inputs for select environment
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        # options for select environment
        options:
          - dev
          - staging
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
